name: tanzania-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=0.25.1
  - numpy=1.16.5
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - geopandas=0.7.0
  - scikit-learn=0.21.2
  - mlxtend=0.17.2
  - scipy=1.3.1